### ISSUE TITLE
Accessing Functional Form of Inferred Transformation

### ISSUE THREAD

**Issue by bking124** [vubiostat/acepack#2]
I'm looking to test out whether the ACE or AVAS methods work for a specific problem of mine.  One thing I was hoping to do was apply the learned transformation to new data, but it seems like only the transformed training data is returned by the functions.  Is there any way to back out an implied transformation that can then be used as a function in R?

On an unrelated note, do you know of any R implementations for other Transform-Both-Sides regression estimators, such as those discussed in the [1995 Wang and Ruppert paper](https://www.tandfonline.com/doi/abs/10.1080/01621459.1995.10476544)?

Thanks in advance for your help!

**Comment by jonbaron1944** [comment]
Brian,

I think this reached me because, for a while, I was the maintainer of the
acepack package, and I had the address of ***@***.*** Now mail to
that old address goes to spam on a different machine, and that is where I found
this.

I think the answer is no. And what you want to do would be very difficult if the
new data input is outside the range of the old data. The problem is that ace and
avas do not look for a function. They transform individual data points. So you
would have at least interpolate, writing your own script to do that. Or fit a
polynomial to the output as a function of the input and then use that.

It may depend a lot on what the transformation look like.

In answering, I am not taking the time to look at the sofware in any way. This
is just a quick response from memory. So it may be wrong.

FWIW, the only time I ever actually used this software is here:
https://www.sas.upenn.edu/~baron/papers/uos.pdf

Jon

On 10/20/22 08:42, Brian King wrote:
> I'm looking to test out whether the ACE or AVAS methods work for a specific problem of mine.  One thing I was hoping to do was apply the learned transformation to new data, but it seems like only the transformed training data is returned by the functions.  Is there any way to back out an implied transformation that can then be used as a function in R?
> 
> On an unrelated note, do you know of any R implementations for other Transform-Both-Sides regression estimators, such as those discussed in the [1995 Wang and Ruppert paper](https://urldefense.com/v3/__https://www.tandfonline.com/doi/abs/10.1080/01621459.1995.10476544)?__;!!IBzWLUs!UQ18FCLv8jSHS-5lfySet_lYmHpO102_YRigbDpm0kTLOu-JXdHA78jqaZ2UYQfFbVODwp6o7JQq7Pg2HpJlpzVDYqR9$  
> 
> Thanks in advance for your help!
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://urldefense.com/v3/__https://github.com/vubiostat/acepack/issues/2__;!!IBzWLUs!UQ18FCLv8jSHS-5lfySet_lYmHpO102_YRigbDpm0kTLOu-JXdHA78jqaZ2UYQfFbVODwp6o7JQq7Pg2HpJlpyKaQw8I$  
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***>

-- 
Jonathan Baron, Professor of Psychology, University of Pennsylvania
Home page: http://www.sas.upenn.edu/~baron
Founding editor: Judgment and Decision Making (http://journal.sjdm.org)
Associate Webmaster: Society for Judgment and Decision Making (https://sjdm.org)

**Comment by jonbaron1944** [comment]
I don't have anything to do with acepack anymore.

On 12/30/24 08:54, Shawn Garbett wrote:
> Closed #2 as completed.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/vubiostat/acepack/issues/2#event-15785813922
> You are receiving this because you commented.
> 
> Message ID: ***@***.***>

-- 
Jonathan Baron, Professor Emeritus of Psychology, University of Pennsylvania
Home page: https://www.sas.upenn.edu/~baron
Founding Editor: Judgment and Decision Making (https://journal.sjdm.org)
